name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Type"
        required: true
        type: choice
        default: "patch"
        options:
        - major
        - minor
        - patch

env:
  PYTHON_LATEST: 3.12

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: read
      contents: write

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

    - name: Install uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7

    - name: Install Python ${{ env.PYTHON_LATEST }}
      env:
        PYTHON_VER: ${{ env.PYTHON_LATEST }}
      run: uv python install "$PYTHON_VER"

    - name: Bump version
      id: bump
      uses: callowayproject/bump-my-version@1f1e0da9e4647e424cdcb736b3cd4d26a8bb70fb # master
      env:
        BUMPVERSION_TAG: "false"
      with:
        args: ${{ inputs.release_type }}
        github-token: ${{ secrets.GH_TOKEN }}
    
    - name: Build
      run: uv build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # release/v1

    - name: GitHub Release PIP v${{ steps.bump.outputs.current-version }}
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
      with:
        name: gh-space-shooter pypi v${{ steps.bump.outputs.current-version }}
        tag: v${{ steps.bump.outputs.current-version }}
        body: "Automated release of pypi version v${{ steps.bump.outputs.current-version }}"
        artifacts: dist/*
        token: ${{ secrets.GH_TOKEN }}
        generateReleaseNotes: true
